name: allset
description: AllSet App
version: 1.1.2+32

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.4.0+8
  firebase_auth: ^0.14.0+2
  cloud_firestore: ^0.12.9
  firebase_messaging: ^5.1.3

  shared_preferences: ^0.5.3+4
  after_layout: ^1.0.7+2

  flutter_masked_text: ^0.8.0
  font_awesome_flutter: ^8.4.0
  percent_indicator: ^1.0.16
  google_maps_flutter: ^0.5.20+6
  geolocator: ^5.1.3
  provider: ^3.1.0

dev_dependencies:
  flutter_launcher_icons: ^0.7.1

flutter_icons:
  android: true
  image_path: 'assets/icon/icon.png'
  adaptive_icon_background: '#212121'
  adaptive_icon_foreground: 'assets/icon/foreground.png'

flutter:
  uses-material-design: true

  fonts:
  - family: OpenSans
    fonts:
    - asset: assets/fonts/OpenSans-Light.ttf
      weight: 300
    - asset: assets/fonts/OpenSans-LightItalic.ttf
      weight: 300
      style: italic
    - asset: assets/fonts/OpenSans-Regular.ttf
      weight: 400
    - asset: assets/fonts/OpenSans-Italic.ttf
      weight: 400
      style: italic
    - asset: assets/fonts/OpenSans-SemiBold.ttf
      weight: 600
    - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
      weight: 600
      style: italic
    - asset: assets/fonts/OpenSans-Bold.ttf
      weight: 700
    - asset: assets/fonts/OpenSans-BoldItalic.ttf
      weight: 700
      style: italic
    - asset: assets/fonts/OpenSans-ExtraBold.ttf
      weight: 800
    - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
      weight: 800
      style: italic