name: AllSet
description: AllSet App
version: 1.0.0+2

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.3.4
  firebase_auth: ^0.8.4+5
  cloud_firestore: ^0.10.0

  shared_preferences: ^0.5.2
  after_layout: ^1.0.7
  qr_flutter: ^2.0.0+51

  font_awesome_flutter: ^8.4.0
  percent_indicator: ^1.0.16

#dev_dependencies:
#  flutter_test:
#    sdk: flutter

flutter:
  uses-material-design: true